export type ToolCategory = "edit" | "organize" | "convert-from" | "convert-to";

export interface Tool {
  id: string;
  name: string;
  slug: string;
  description: string;
  longDescription: string;
  icon: string;
  category: ToolCategory;
  color: string;
  bgColor: string;
  metaTitle: string;
  metaDescription: string;
  benefits: string[];
  faqs: { question: string; answer: string }[];
  relatedTools: string[];
}

export const tools: Tool[] = [
  {
    id: "edit-pdf",
    name: "Edit PDF",
    slug: "edit-pdf",
    description: "Edit text, images and content in any PDF file online.",
    longDescription: "Modify your PDF documents directly in your browser. Add, edit or remove text, images and other content without any software installation.",
    icon: "FileEdit",
    category: "edit",
    color: "#2563EB",
    bgColor: "#EFF6FF",
    metaTitle: "Edit PDF Online Free – Modify Text & Images | PDFCraft",
    metaDescription: "Edit PDF files online for free. Add text, images, and annotations. No software needed. Fast, secure, and easy to use.",
    benefits: [
      "Edit any PDF directly in your browser",
      "No software installation required",
      "Secure and private — files deleted after processing",
      "Works on desktop and mobile",
    ],
    faqs: [
      { question: "Can I edit any PDF?", answer: "Yes, PDFCraft supports editing text, images, and other elements in most standard PDF files." },
      { question: "Is editing free?", answer: "You can preview and edit for free. Downloading the edited PDF requires a premium plan." },
    ],
    relatedTools: ["add-text-pdf", "annotate-pdf", "sign-pdf"],
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    slug: "sign-pdf",
    description: "Add your signature to PDF documents online, instantly.",
    longDescription: "Create legally-binding digital signatures and apply them to any PDF. Draw, type, or upload your signature in seconds.",
    icon: "PenLine",
    category: "edit",
    color: "#7C3AED",
    bgColor: "#F5F3FF",
    metaTitle: "Sign PDF Online Free – Digital Signature Tool | PDFCraft",
    metaDescription: "Add your digital signature to PDFs online. Draw, type or upload a signature. Legally binding and secure.",
    benefits: [
      "Draw, type, or upload your signature",
      "Legally recognized digital signatures",
      "Sign multiple pages at once",
      "No account required to get started",
    ],
    faqs: [
      { question: "Are digital signatures legally valid?", answer: "Yes, digital signatures created with PDFCraft comply with eSign standards and are legally binding in most countries." },
      { question: "Can I sign multiple documents?", answer: "Premium users can sign unlimited documents. Free users can sign and preview one document at a time." },
    ],
    relatedTools: ["edit-pdf", "fill-pdf", "add-text-pdf"],
  },
  {
    id: "fill-pdf",
    name: "Fill PDF Forms",
    slug: "fill-pdf",
    description: "Fill out PDF forms and fields online without any app.",
    longDescription: "Easily fill in text fields, checkboxes, radio buttons and other form elements in any PDF file directly in your browser.",
    icon: "ClipboardList",
    category: "edit",
    color: "#059669",
    bgColor: "#ECFDF5",
    metaTitle: "Fill PDF Forms Online Free – No Software Needed | PDFCraft",
    metaDescription: "Fill out PDF forms online instantly. Enter text in form fields, check boxes, and sign. Works on any device.",
    benefits: [
      "Fill any PDF form field instantly",
      "Works with interactive and non-interactive PDFs",
      "Save time with auto-detection of form fields",
      "Secure and private processing",
    ],
    faqs: [
      { question: "What types of fields can I fill?", answer: "Text boxes, checkboxes, radio buttons, dropdown menus, and signature fields." },
      { question: "Does it work with scanned PDFs?", answer: "For scanned PDFs, our OCR feature detects form areas. Some fields may need manual positioning." },
    ],
    relatedTools: ["sign-pdf", "edit-pdf", "annotate-pdf"],
  },
  {
    id: "annotate-pdf",
    name: "Annotate PDF",
    slug: "annotate-pdf",
    description: "Add comments, notes and markups to any PDF document.",
    longDescription: "Review and annotate PDFs with sticky notes, comments, stamps, and markup tools. Perfect for collaboration and document review.",
    icon: "MessageSquare",
    category: "edit",
    color: "#D97706",
    bgColor: "#FFFBEB",
    metaTitle: "Annotate PDF Online Free – Add Comments & Notes | PDFCraft",
    metaDescription: "Annotate PDFs online. Add sticky notes, comments, stamps and text markup. Perfect for document review and collaboration.",
    benefits: [
      "Add sticky notes and comments",
      "Stamp documents with labels",
      "Markup text with arrows and shapes",
      "Share annotated PDFs easily",
    ],
    faqs: [
      { question: "Can others see my annotations?", answer: "Yes, annotations are embedded in the PDF so anyone who opens it will see them." },
      { question: "Can I remove annotations later?", answer: "Yes, you can edit or delete any annotation before downloading." },
    ],
    relatedTools: ["highlight-pdf", "edit-pdf", "draw-pdf"],
  },
  {
    id: "add-text-pdf",
    name: "Add Text to PDF",
    slug: "add-text-pdf",
    description: "Insert custom text anywhere in your PDF documents.",
    longDescription: "Place text boxes anywhere on your PDF pages. Choose font, size, color and style. Perfect for filling in forms or adding labels.",
    icon: "Type",
    category: "edit",
    color: "#2563EB",
    bgColor: "#EFF6FF",
    metaTitle: "Add Text to PDF Online Free – Insert Text Anywhere | PDFCraft",
    metaDescription: "Add custom text to any PDF online. Choose font, size and color. No software installation required.",
    benefits: [
      "Place text anywhere on any page",
      "Full font and color customization",
      "Works on any operating system",
      "No watermarks on free previews",
    ],
    faqs: [
      { question: "What fonts are available?", answer: "We offer a wide selection of web-safe and premium fonts including Helvetica, Arial, Times New Roman, and many more." },
      { question: "Can I edit text I've already added?", answer: "Yes, all text elements can be selected, edited, moved, or deleted before downloading." },
    ],
    relatedTools: ["edit-pdf", "annotate-pdf", "fill-pdf"],
  },
  {
    id: "highlight-pdf",
    name: "Highlight PDF",
    slug: "highlight-pdf",
    description: "Highlight text in PDFs with colors and markups online.",
    longDescription: "Use digital highlighters to mark important text in your PDFs. Choose from multiple colors and quickly review key content.",
    icon: "Highlighter",
    category: "edit",
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    metaTitle: "Highlight PDF Online Free – Mark Important Text | PDFCraft",
    metaDescription: "Highlight text in PDF files online. Choose highlight colors, underline, or strikethrough text. Easy and fast.",
    benefits: [
      "Multiple highlight colors available",
      "Underline and strikethrough tools",
      "Non-destructive — original text preserved",
      "Great for studying and document review",
    ],
    faqs: [
      { question: "Can I highlight scanned PDFs?", answer: "For scanned PDFs, our tool uses OCR to detect text that can then be highlighted." },
      { question: "Does highlighting change the original text?", answer: "No, highlighting only adds a visual layer. The original text remains intact." },
    ],
    relatedTools: ["annotate-pdf", "add-text-pdf", "edit-pdf"],
  },
  {
    id: "draw-pdf",
    name: "Draw on PDF",
    slug: "draw-pdf",
    description: "Freehand drawing and sketching on PDF documents.",
    longDescription: "Use our drawing tools to sketch, draw arrows, shapes, or freehand annotations directly on your PDF pages.",
    icon: "Pencil",
    category: "edit",
    color: "#EC4899",
    bgColor: "#FDF2F8",
    metaTitle: "Draw on PDF Online Free – Freehand Drawing Tool | PDFCraft",
    metaDescription: "Draw freehand on PDF files online. Add sketches, arrows, shapes and drawings. No app download required.",
    benefits: [
      "Freehand pen and brush tools",
      "Draw shapes, arrows and lines",
      "Adjustable pen size and opacity",
      "Touch-friendly for tablet users",
    ],
    faqs: [
      { question: "Can I use this on a tablet?", answer: "Yes, our drawing tool is fully optimized for touch devices including tablets and stylus input." },
      { question: "Can I erase my drawings?", answer: "Yes, there's an eraser tool and you can also undo any stroke with Ctrl+Z." },
    ],
    relatedTools: ["annotate-pdf", "highlight-pdf", "edit-pdf"],
  },
  {
    id: "add-image-pdf",
    name: "Add Image to PDF",
    slug: "add-image-pdf",
    description: "Insert photos and images into any PDF document online.",
    longDescription: "Upload and place images anywhere in your PDF. Resize, rotate, and position images with precision using our drag-and-drop editor.",
    icon: "Image",
    category: "edit",
    color: "#0891B2",
    bgColor: "#ECFEFF",
    metaTitle: "Add Image to PDF Online Free – Insert Photos | PDFCraft",
    metaDescription: "Add images and photos to PDF files online. Insert, resize and position images anywhere. Fast and free to try.",
    benefits: [
      "Drag and drop image placement",
      "Supports JPG, PNG, GIF, WEBP",
      "Resize and rotate images freely",
      "Adjust image transparency",
    ],
    faqs: [
      { question: "What image formats are supported?", answer: "JPG, JPEG, PNG, GIF, WEBP and SVG files can be inserted into your PDF." },
      { question: "Is there a limit on image size?", answer: "Free users can upload images up to 5MB each. Premium users have a 25MB limit per image." },
    ],
    relatedTools: ["edit-pdf", "draw-pdf", "annotate-pdf"],
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "merge-pdf",
    description: "Combine multiple PDFs into one single document.",
    longDescription: "Merge two or more PDF files into a single document. Drag and drop to reorder pages before combining.",
    icon: "Combine",
    category: "organize",
    color: "#2563EB",
    bgColor: "#EFF6FF",
    metaTitle: "Merge PDF Files Online Free – Combine PDFs | PDFCraft",
    metaDescription: "Merge multiple PDF files into one. Drag and drop to reorder. Fast, free PDF merger — no software needed.",
    benefits: [
      "Merge unlimited PDF files",
      "Reorder files before merging",
      "Maintain original quality",
      "No file size limits on premium",
    ],
    faqs: [
      { question: "How many files can I merge at once?", answer: "Free users can merge up to 2 files. Premium users can merge unlimited files at once." },
      { question: "Will the quality be affected?", answer: "No, PDFCraft merges PDFs without re-encoding, preserving the original quality." },
    ],
    relatedTools: ["split-pdf", "reorder-pages", "compress-pdf"],
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "split-pdf",
    description: "Split a PDF into multiple separate documents.",
    longDescription: "Divide your PDF into individual pages or custom page ranges. Extract specific pages from large documents quickly.",
    icon: "Scissors",
    category: "organize",
    color: "#7C3AED",
    bgColor: "#F5F3FF",
    metaTitle: "Split PDF Online Free – Separate Pages | PDFCraft",
    metaDescription: "Split PDF files into multiple documents online. Extract specific pages or ranges. Free PDF splitter tool.",
    benefits: [
      "Split into individual pages",
      "Extract custom page ranges",
      "Split by file size",
      "Batch download all split files",
    ],
    faqs: [
      { question: "Can I extract just specific pages?", answer: "Yes, you can specify exact page numbers or ranges (e.g. 1-3, 5, 8-10) to extract." },
      { question: "How do I download the split files?", answer: "Split files are packaged in a ZIP download. Premium users also get individual page downloads." },
    ],
    relatedTools: ["merge-pdf", "delete-pages", "reorder-pages"],
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    slug: "compress-pdf",
    description: "Reduce PDF file size without sacrificing quality.",
    longDescription: "Compress large PDF files to make them easier to share and upload. Choose your compression level to balance size and quality.",
    icon: "Minimize2",
    category: "organize",
    color: "#059669",
    bgColor: "#ECFDF5",
    metaTitle: "Compress PDF Online Free – Reduce File Size | PDFCraft",
    metaDescription: "Compress PDF files online to reduce file size. Preserve quality while making PDFs smaller. Free PDF compressor.",
    benefits: [
      "Up to 90% file size reduction",
      "Multiple compression levels",
      "Batch compress multiple files",
      "Maintains readable quality",
    ],
    faqs: [
      { question: "How much can I reduce the file size?", answer: "Typical compression rates are 30-80%, depending on the original content. Image-heavy PDFs compress more." },
      { question: "Will compressing affect the text quality?", answer: "Text remains crisp at all compression levels. Only image resolution is adjusted when compressing." },
    ],
    relatedTools: ["merge-pdf", "pdf-to-jpg", "split-pdf"],
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    slug: "rotate-pdf",
    description: "Rotate PDF pages by 90° or 180° in any direction.",
    longDescription: "Fix the orientation of your PDF pages. Rotate all pages or select individual pages to rotate independently.",
    icon: "RotateCw",
    category: "organize",
    color: "#D97706",
    bgColor: "#FFFBEB",
    metaTitle: "Rotate PDF Pages Online Free – Fix Orientation | PDFCraft",
    metaDescription: "Rotate PDF pages online. Fix upside-down or sideways pages. Rotate individual pages or all at once.",
    benefits: [
      "Rotate clockwise or counter-clockwise",
      "Rotate individual or all pages",
      "Preview before saving",
      "Fast single-click rotation",
    ],
    faqs: [
      { question: "Can I rotate just one page?", answer: "Yes, you can select any combination of pages and rotate them independently." },
      { question: "Are rotations permanent?", answer: "Yes, the rotation is saved permanently to the PDF when you download." },
    ],
    relatedTools: ["delete-pages", "reorder-pages", "merge-pdf"],
  },
  {
    id: "delete-pages",
    name: "Delete PDF Pages",
    slug: "delete-pages",
    description: "Remove unwanted pages from your PDF documents.",
    longDescription: "Select and delete specific pages from any PDF file. Preview all pages and choose which ones to remove before saving.",
    icon: "Trash2",
    category: "organize",
    color: "#EF4444",
    bgColor: "#FEF2F2",
    metaTitle: "Delete PDF Pages Online Free – Remove Pages | PDFCraft",
    metaDescription: "Delete pages from PDF files online. Select and remove any pages. Preview before saving. Free PDF page remover.",
    benefits: [
      "Visual page preview before deleting",
      "Delete multiple pages at once",
      "Maintains document formatting",
      "Undo support before download",
    ],
    faqs: [
      { question: "Can I delete multiple pages at once?", answer: "Yes, select multiple pages by clicking them, then delete all at once." },
      { question: "Can I undo a deletion?", answer: "Yes, you can undo deletions before downloading. Once downloaded, the action is permanent." },
    ],
    relatedTools: ["split-pdf", "reorder-pages", "rotate-pdf"],
  },
  {
    id: "reorder-pages",
    name: "Reorder PDF Pages",
    slug: "reorder-pages",
    description: "Drag and drop to rearrange pages in your PDF.",
    longDescription: "Rearrange the order of pages in your PDF with an intuitive drag-and-drop interface. Preview every page as a thumbnail.",
    icon: "GripVertical",
    category: "organize",
    color: "#0891B2",
    bgColor: "#ECFEFF",
    metaTitle: "Reorder PDF Pages Online Free – Rearrange Pages | PDFCraft",
    metaDescription: "Rearrange PDF pages online with drag and drop. Reorder, organize and rearrange pages easily. Free tool.",
    benefits: [
      "Drag-and-drop page reordering",
      "Thumbnail preview of all pages",
      "Quick first/last page shortcuts",
      "Works with large PDFs",
    ],
    faqs: [
      { question: "Is there a page limit?", answer: "Free users can reorder up to 20 pages. Premium users have no page limit." },
      { question: "Can I combine reordering with other edits?", answer: "Yes, after reordering you can continue to edit, annotate or compress in the same session." },
    ],
    relatedTools: ["delete-pages", "merge-pdf", "split-pdf"],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    slug: "pdf-to-word",
    description: "Convert PDF documents to editable Word files (DOCX).",
    longDescription: "Transform any PDF into a fully editable Microsoft Word document. Preserves formatting, tables, and images.",
    icon: "FileText",
    category: "convert-from",
    color: "#2563EB",
    bgColor: "#EFF6FF",
    metaTitle: "PDF to Word Converter Online Free – PDF to DOCX | PDFCraft",
    metaDescription: "Convert PDF to Word online. Get editable DOCX files with preserved formatting. Fast, accurate PDF to Word converter.",
    benefits: [
      "Accurate layout preservation",
      "Tables and images included",
      "Works with scanned PDFs via OCR",
      "No Microsoft Word required",
    ],
    faqs: [
      { question: "Does it preserve the original formatting?", answer: "Yes, PDFCraft preserves fonts, tables, columns, and images during PDF to Word conversion." },
      { question: "Can I convert scanned PDFs?", answer: "Yes, our OCR technology recognizes text from scanned documents and converts them to editable Word files." },
    ],
    relatedTools: ["pdf-to-jpg", "pdf-to-png", "word-to-pdf"],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    slug: "pdf-to-jpg",
    description: "Convert each PDF page to a high-quality JPG image.",
    longDescription: "Export PDF pages as high-resolution JPG images. Choose image quality and download individually or as a ZIP archive.",
    icon: "ImageDown",
    category: "convert-from",
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    metaTitle: "PDF to JPG Converter Online Free – Convert PDF to Image | PDFCraft",
    metaDescription: "Convert PDF pages to JPG images online. High-quality conversion, multiple pages at once. Free PDF to JPG converter.",
    benefits: [
      "High-resolution output",
      "Custom DPI settings",
      "Convert all pages at once",
      "Download as ZIP archive",
    ],
    faqs: [
      { question: "What resolution are the output images?", answer: "Default output is 150 DPI. Premium users can export at up to 600 DPI for print-quality images." },
      { question: "Can I convert just one page?", answer: "Yes, you can select which pages to convert before downloading." },
    ],
    relatedTools: ["pdf-to-png", "pdf-to-word", "jpg-to-pdf"],
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    slug: "pdf-to-png",
    description: "Export PDF pages as transparent PNG images.",
    longDescription: "Convert PDF pages to lossless PNG images with transparency support. Perfect for presentations and design work.",
    icon: "ImageDown",
    category: "convert-from",
    color: "#7C3AED",
    bgColor: "#F5F3FF",
    metaTitle: "PDF to PNG Converter Online Free – PDF to Image | PDFCraft",
    metaDescription: "Convert PDF to PNG images online. Lossless quality, transparent backgrounds supported. Free PDF to PNG tool.",
    benefits: [
      "Lossless PNG quality",
      "Transparency support",
      "Higher quality than JPG",
      "Batch convert all pages",
    ],
    faqs: [
      { question: "What is the difference between PDF to JPG and PDF to PNG?", answer: "PNG is lossless and supports transparency, making it ideal for logos and design work. JPG is smaller in file size but may lose some quality." },
      { question: "Can I get transparent backgrounds?", answer: "Yes, if the original PDF has a transparent background, PNG output will preserve it." },
    ],
    relatedTools: ["pdf-to-jpg", "pdf-to-word", "jpg-to-pdf"],
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    slug: "word-to-pdf",
    description: "Convert Word documents (DOCX) to PDF instantly.",
    longDescription: "Upload any .doc or .docx file and convert it to a professional-looking PDF in seconds. No Word installation needed.",
    icon: "FilePlus",
    category: "convert-to",
    color: "#2563EB",
    bgColor: "#EFF6FF",
    metaTitle: "Word to PDF Converter Online Free – DOCX to PDF | PDFCraft",
    metaDescription: "Convert Word to PDF online. Accurate formatting, free Word to PDF converter. Works with .doc and .docx files.",
    benefits: [
      "Perfect format preservation",
      "No Word installation needed",
      "Supports .doc and .docx files",
      "Instant conversion",
    ],
    faqs: [
      { question: "Does it preserve fonts?", answer: "Yes, all fonts, styles, and formatting are preserved in the PDF output." },
      { question: "Are there file size limits?", answer: "Free users can convert files up to 10MB. Premium users have a 100MB limit per file." },
    ],
    relatedTools: ["pdf-to-word", "excel-to-pdf", "ppt-to-pdf"],
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    slug: "jpg-to-pdf",
    description: "Convert JPG images to PDF documents online.",
    longDescription: "Combine one or multiple JPG images into a PDF. Control page size, orientation, and image quality.",
    icon: "FilePlus",
    category: "convert-to",
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    metaTitle: "JPG to PDF Converter Online Free – Image to PDF | PDFCraft",
    metaDescription: "Convert JPG images to PDF online. Combine multiple images into one PDF. Free JPG to PDF converter.",
    benefits: [
      "Convert single or multiple images",
      "Custom page size and margin",
      "Drag-and-drop ordering",
      "High-quality output",
    ],
    faqs: [
      { question: "Can I combine multiple JPGs into one PDF?", answer: "Yes, upload multiple images and they'll be converted to separate pages in a single PDF." },
      { question: "Does the image quality change?", answer: "No, we preserve the original image quality unless you choose to optimize the output." },
    ],
    relatedTools: ["pdf-to-jpg", "pdf-to-png", "word-to-pdf"],
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    slug: "excel-to-pdf",
    description: "Convert Excel spreadsheets to PDF with layout intact.",
    longDescription: "Transform .xls and .xlsx files into professional PDFs. All spreadsheet formatting, charts, and tables are preserved.",
    icon: "TableProperties",
    category: "convert-to",
    color: "#059669",
    bgColor: "#ECFDF5",
    metaTitle: "Excel to PDF Converter Online Free – XLS to PDF | PDFCraft",
    metaDescription: "Convert Excel files to PDF online. Preserve tables, charts and formatting. Free Excel to PDF converter.",
    benefits: [
      "Preserves all Excel formatting",
      "Tables and charts included",
      "Supports .xls and .xlsx",
      "Print-ready PDF output",
    ],
    faqs: [
      { question: "Will my charts be included?", answer: "Yes, all charts, graphs, and visual elements are preserved in the PDF conversion." },
      { question: "Does it support merged cells?", answer: "Yes, merged cells, conditional formatting, and most Excel features are preserved." },
    ],
    relatedTools: ["word-to-pdf", "ppt-to-pdf", "pdf-to-word"],
  },
  {
    id: "ppt-to-pdf",
    name: "PPT to PDF",
    slug: "ppt-to-pdf",
    description: "Convert PowerPoint presentations to PDF slides.",
    longDescription: "Export any .ppt or .pptx file as a high-quality PDF. Each slide becomes a PDF page with all animations noted.",
    icon: "Presentation",
    category: "convert-to",
    color: "#EF4444",
    bgColor: "#FEF2F2",
    metaTitle: "PowerPoint to PDF Converter Online Free – PPT to PDF | PDFCraft",
    metaDescription: "Convert PowerPoint to PDF online. Each slide exported as a PDF page. Free PPT to PDF converter.",
    benefits: [
      "Each slide becomes a PDF page",
      "Preserves images and text",
      "Works without PowerPoint",
      "Supports .ppt and .pptx",
    ],
    faqs: [
      { question: "Are slide transitions preserved?", answer: "Animations and transitions are not preserved in PDF format, but all content, layouts, and media are included." },
      { question: "Can I choose which slides to convert?", answer: "Premium users can select specific slide ranges to convert." },
    ],
    relatedTools: ["word-to-pdf", "excel-to-pdf", "pdf-to-word"],
  },
];

export const toolsByCategory = {
  edit: tools.filter((t) => t.category === "edit"),
  organize: tools.filter((t) => t.category === "organize"),
  "convert-from": tools.filter((t) => t.category === "convert-from"),
  "convert-to": tools.filter((t) => t.category === "convert-to"),
};

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getRelatedTools(toolId: string): Tool[] {
  const tool = tools.find((t) => t.id === toolId);
  if (!tool) return [];
  return tool.relatedTools
    .map((slug) => tools.find((t) => t.id === slug))
    .filter(Boolean) as Tool[];
}

// ─── Editor-based tools ───────────────────────────────────────────────────────
// Tools that open the PDF editor with a specific tool pre-selected.
// Key = tool slug, value = editor ToolAction to activate.
export const EDITOR_TOOL_MAP: Record<string, string> = {
  "edit-pdf":      "pointer",
  "sign-pdf":      "sign",
  "fill-pdf":      "add-text",
  "annotate-pdf":  "draw",
  "add-text-pdf":  "add-text",
  "highlight-pdf": "highlight",
  "draw-pdf":      "draw",
  "add-image-pdf": "add-image",
  "rotate-pdf":    "rotate",
  "delete-pages":  "delete-page",
};

// ─── Coming-soon tools ────────────────────────────────────────────────────────
// These require server-side PDF processing and are not yet implemented.
export const COMING_SOON_TOOLS = new Set([
  "merge-pdf",
  "split-pdf",
  "compress-pdf",
  "reorder-pages",
  "pdf-to-word",
  "pdf-to-jpg",
  "pdf-to-png",
  "word-to-pdf",
  "jpg-to-pdf",
  "excel-to-pdf",
  "ppt-to-pdf",
]);
